import { StyleSheet } from "@react-pdf/renderer";

/** Dark-theme palette aligned with the Muhaj web UI. */
export const PDF_COLORS = {
  background: "#0B0F12",
  surface: "#12161A",
  surfaceAlt: "#1A1F24",
  border: "rgba(255,255,255,0.08)",
  primary: "#062E03",
  emerald: "#1A6B4F",
  gold: "#D4AF37",
  goldLight: "#E8C96A",
  hussain: "#C41E3A",
  text: "#F4F4F5",
  muted: "#71717A",
  mutedLight: "#A1A1AA",
  amber: "#F59E0B",
};

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: PDF_COLORS.text,
    backgroundColor: PDF_COLORS.background,
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    gap: 8,
  },
  logoTextBlock: {
    alignItems: "center",
  },
  logoArabic: {
    fontFamily: "Arabic",
    fontSize: 28,
    fontWeight: 700,
    color: PDF_COLORS.gold,
    marginBottom: 2,
  },
  logoSubtitle: {
    fontSize: 8,
    color: PDF_COLORS.muted,
    letterSpacing: 0.5,
  },
  duaBlock: {
    marginBottom: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
    alignItems: "center",
  },
  duaArabic: {
    fontFamily: "Arabic",
    fontSize: 14,
    fontWeight: 700,
    textAlign: "center",
    lineHeight: 1.6,
    marginBottom: 6,
  },
  duaGold: {
    fontFamily: "Arabic",
    color: PDF_COLORS.goldLight,
  },
  duaHussain: {
    fontFamily: "Arabic",
    color: PDF_COLORS.hussain,
  },
  duaTranslation: {
    fontSize: 8,
    color: PDF_COLORS.mutedLight,
    textAlign: "center",
    lineHeight: 1.4,
    maxWidth: 420,
  },
  docTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.gold,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  subtitle: {
    fontSize: 8,
    color: PDF_COLORS.muted,
    marginBottom: 14,
  },
  securityFlap: {
    backgroundColor: PDF_COLORS.surface,
    borderWidth: 1,
    borderColor: PDF_COLORS.gold,
    borderRadius: 6,
    padding: 12,
    marginBottom: 14,
  },
  securityTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.gold,
    marginBottom: 5,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  securityText: {
    fontSize: 9,
    color: PDF_COLORS.mutedLight,
    marginBottom: 3,
    lineHeight: 1.4,
  },
  sectionHeader: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.gold,
    marginTop: 10,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.emerald,
  },
  dayBlockEven: {
    backgroundColor: PDF_COLORS.surface,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
  },
  dayBlockOdd: {
    backgroundColor: PDF_COLORS.surfaceAlt,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
  },
  dayTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.goldLight,
    marginBottom: 4,
  },
  line: {
    fontSize: 9,
    color: PDF_COLORS.mutedLight,
    marginBottom: 2,
    lineHeight: 1.35,
  },
  emergencyBox: {
    marginTop: 12,
    backgroundColor: PDF_COLORS.primary,
    padding: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: PDF_COLORS.emerald,
  },
  emergencyTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.gold,
    marginBottom: 6,
  },
  emergencyLine: {
    fontSize: 8,
    color: PDF_COLORS.text,
    marginBottom: 3,
    lineHeight: 1.35,
  },
});
